ktor:
  environment: production
  development: true
  deployment:
    port: 8080
    host: 0.0.0.0
  watch:
    - classes
    - resources
  application:
    modules:
      - "io.greedy.goblin.api.ApplicationKt.module"
  database:
    url: "jdbc:postgresql://pg_goblin:5432/postgres"
    driver: "org.postgresql.Driver"
    username: "admin"
    password: "admin"
    poolSize: 10
    isolation: "TRANSACTION_REPEATABLE_READ"


  #  urls:
#    - "http://127.0.0.1:8080/v1"
#    - "http://0.0.0.0:8080/v1"
#    - "http://192.168.0.182:8080/v1"
  logger: logback
#  # Логирование типа socket требует установки в fluent-bit.conf
#  # [INPUT]
#  # Name    TCP # Вот здесь нужно поменять!
#  # Listen  0.0.0.0
#  # Port    24224
#  logger: socket
#  socketLogger:
#    port: 24224
