openapi: 3.0.4
info:
  title: "Greedy Goblin Game API"
  description: API for managing game sessions, scenes, and player actions in the Greedy Goblin game.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
tags:
  - name: game
    description: Game session and scene management

paths:
  /game/start:
    post:
      tags:
        - game
      summary: Start a new game session
      operationId: startGame
      requestBody:
        description: Request to start a new game session
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GameStartRequest'
        required: true
      responses:
        200:
          description: Game started successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameStartResponse'

  /game/scene:
    get:
      tags:
        - game
      summary: Retrieve the current active scene
      operationId: getActiveScene
      responses:
        200:
          description: Successfully retrieved the current scene
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SceneResponse'

  /game/action:
    post:
      tags:
        - game
      summary: Perform an action in the current scene
      operationId: performAction
      requestBody:
        description: Action chosen by the player
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ActionRequest'
        required: true
      responses:
        200:
          description: Action performed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionResponse'

  /game/end:
    post:
      tags:
        - game
      summary: End the current game session
      operationId: endGame
      requestBody:
        description: Request to end the game session
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GameEndRequest'
        required: true
      responses:
        200:
          description: Game session ended successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameEndResponse'

components:
  schemas:
    BaseResponse:
      type: object
      properties:
        success:
          type: boolean
          description: Indicates if the request was successful
        message:
          type: string
          description: Optional message with details (e.g., error description)

    GameStartRequest:
      type: object
      properties:
        mode:
          type: string
          enum:
            - single
          description: Mode of game

    GameStartResponse:
      allOf:
        - $ref: '#/components/schemas/BaseResponse'
        - type: object
          properties:
            gameId:
              type: string
              description: Unique identifier for the new game session

    Scene:
      type: object
      properties:
        sceneId:
          type: string
          description: Unique identifier of the scene
        gameId:
          type: string
          description: ID of the game session
        image:
          type: string
          description: URI of the scene's image
        description:
          type: string
          description: Brief text describing the scene
        actions:
          type: array
          items:
            type: string
          description: Available actions the player can choose

    SceneResponse:
      allOf:
        - $ref: '#/components/schemas/BaseResponse'
        - type: object
          properties:
            scene:
              $ref: '#/components/schemas/Scene'

    ActionRequest:
      type: object
      properties:
        action:
          type: string
          description: Action chosen by the player

    ActionResponse:
      allOf:
        - $ref: '#/components/schemas/BaseResponse'

    GameEndRequest:
      type: object
      properties:
        gameId:
          type: string
          description: ID of the game session to end

    GameEndResponse:
      allOf:
        - $ref: '#/components/schemas/BaseResponse'
